### ISSUE TITLE
Files (Destination) Not Working

### ISSUE THREAD

**Issue by coolspot18** [AxionDrak/GameCube-Backup-Manager#105]
### Discussed in https://github.com/AxionDrak/GameCube-Backup-Manager/discussions/104

<div type='discussions-op-text'>

<sup>Originally posted by **coolspot18** October 25, 2022</sup>
Hello,

I am facing a lot of trouble with the application (v2.6.1.2), app crashes on the Files (Destination) tab:

Steps to reproduce:

1. Start the application
2. Select Files (Destination) Tab
3. Select E:\ Drive

![image](https://user-images.githubusercontent.com/5160442/197861045-ea112b90-a9a0-4287-abdd-133bc6a4d4a3.png)

4. ISOs are listed
5. Click on an entry: 

![image](https://user-images.githubusercontent.com/5160442/197862133-2f8859e7-54dc-485c-ad84-9eb5f3fa45a6.png)

2022-10-25 14:00:52] [INFO] Sequence contains no elementsSequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at GCBM.frmMain.<ReloadDataGridViewGameList>d__16.MoveNext()[2022-10-25 14:00:53] [INFO] Sequence contains no elementsSequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at GCBM.frmMain.<ReloadDataGridViewGameList>d__16.MoveNext()[2022-10-25 14:00:54] [INFO] Sequence contains no elementsSequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)

Also, when I click on an entry, the details are blank:

![image](https://user-images.githubusercontent.com/5160442/197861532-0e2055e7-6c7e-4da0-85dd-70dcd9d57bfe.png)
</div>

**Comment by sjohnson1021** [comment]
Fixed in the latest update. My apologies. thank you for pointing this out, and your patience.
