### ISSUE TITLE
there is problem about integer sizes while loading iso files

### ISSUE THREAD

**Issue by killerkirb** [AxionDrak/GameCube-Backup-Manager#115]
************** Exception Text **************
System.OverflowException: Value was either too large or too small for an Int32.
   at System.Convert.ToInt32(Int64 value)
   at GCBM.Game..ctor(String path, Boolean useXmlTitle)
   at GCBM.frmMain.<DisplaySourceFilesAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at GCBM.frmMain.<tsmiReloadGameList_Click>d__139.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

**Comment by killerkirb** [comment]
![image](https://user-images.githubusercontent.com/107715222/229877743-b7968b1e-1f3c-4589-af72-178eb12122a6.png)

**Comment by sjohnson1021** [comment]
Could you provide maybe info about the format(s) or files you're trying to load? Like.. is it a custom image/mod? Are you maybe opening a directory with non GameCube images? Or.. this is obviously failing on a specific file.. will try to look into this with the info provided, maybe push a build with more detailed error information (Error logging system is.. kind of there, but not well implemented and definitely needs attention.)

**Comment by killerkirb** [comment]
it is only super mario sunshine iso nothing is there exept that

**Comment by jalbertdev** [comment]
I am experiencing the same issue trying to sync a bunch of ISOs and the error doens't really tell me which file is the issue -_-

**Comment by killerkirb** [comment]
i think i was solved the issue by setting split size or something like that it been years so i forgot anyway im closing this issue
