### ISSUE TITLE
Issue loading ISOs (Value was either too large or too small for an Int32.)

### ISSUE THREAD

**Issue by jalbertdev** [AxionDrak/GameCube-Backup-Manager#127]
I keep getting the error:
[2024-02-28 15:45:55] [ERROR] Value was either too large or too small for an Int32.
   at System.Convert.ToInt32(Int64 value)
   at GCBM.Game..ctor(String path, Boolean useXmlTitle)
   at GCBM.frmMain.<DisplaySourceFilesAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at GCBM.frmMain.<btnSelectFolder_Click>d__46.MoveNext()

I am unsure which file is causing this but there isn't enough logging to tell :/

**Comment by jalbertdev** [comment]
So I realized that I accidentally snuck my brawl iso in. May be nice if we have any good error checking for this case instead of a generic int32 error
